# Generated by Django 2.1.4 on 2019-01-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='comment_status',
            field=models.SmallIntegerField(choices=[(0, 'open'), (1, 'closed')], default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='menu_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_status',
            field=models.SmallIntegerField(choices=[(0, 'publish'), (1, 'auto-draft'), (2, 'inherit')], default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.SmallIntegerField(choices=[(0, '原创'), (1, '转载')], default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='terms',
            field=models.ManyToManyField(blank=True, null=True, to='app.Terms'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
